# This workflow will install Python dependencies, run tests and lint.
name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  checks:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install poetry
        run: |
          pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Install dependencies
        run: |
          poetry env use 3.10
          poetry install

      - name: Verify formatting
        run: |
          poetry run ruff . --select I
          poetry run black --check .

      - name: Lint
        run: |
          poetry run ruff . --exit-zero
          poetry run mypy --install-types --non-interactive .
